# Generated by Django 5.1.4 on 2025-04-02 06:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_nottouchedoption_questionpg_questionug_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nottouchedoption',
            name='not_touched_question_list',
        ),
        migrations.AddField(
            model_name='nottouchedoption',
            name='not_touched_questions_pg',
            field=models.ManyToManyField(blank=True, to='exam.questionpg'),
        ),
        migrations.AddField(
            model_name='nottouchedoption',
            name='not_touched_questions_ug',
            field=models.ManyToManyField(blank=True, to='exam.questionug'),
        ),
        migrations.AddField(
            model_name='questionpg',
            name='subject',
            field=models.CharField(choices=[('MBA', 'MBA'), ('MCA', 'MCA'), ('MA', 'MA'), ('M.Com', 'M.Com')], default='MBA', max_length=255),
        ),
        migrations.AddField(
            model_name='questionug',
            name='subject',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics'), ('Biology', 'Biology'), ('English', 'English')], default='Physics', max_length=255),
        ),
        migrations.AddField(
            model_name='result',
            name='question_pg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.questionpg'),
        ),
        migrations.AddField(
            model_name='result',
            name='question_ug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.questionug'),
        ),
        migrations.AlterField(
            model_name='questionpg',
            name='correct_option',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1, validators=[django.core.validators.RegexValidator(message='Correct option must be A, B, C, or D.', regex='^[A-D]$')]),
        ),
        migrations.AlterField(
            model_name='questionug',
            name='correct_option',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1, validators=[django.core.validators.RegexValidator(message='Correct option must be A, B, C, or D.', regex='^[A-D]$')]),
        ),
        migrations.AlterField(
            model_name='result',
            name='selected_option',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1, validators=[django.core.validators.RegexValidator(message='Selected option must be A, B, C, or D.', regex='^[A-D]$')]),
        ),
    ]
