# Generated by Django 5.1.4 on 2025-04-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_questionpg_main_subject_alter_questionpg_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpg',
            name='main_subject',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Mathematics', 'Mathematics'), ('Reasoning', 'Reasoning'), ('Computer', 'Computer'), ('Micro Ecomonics', 'Micro Ecomonics'), ('Currency and banking', 'Currency and banking'), ('Accounting', 'Accounting'), ('Company law', 'Company law'), ('Business maths', 'Business maths'), ('Indian writing', 'Indian writing'), ('Literary terms', 'Literary terms'), ('Literary genres', 'Literary genres'), ('Literary criticism', 'Literary criticism'), ('Rachnakar', 'Rachnakar'), ('Kaal vibhajan', 'Kaal vibhajan'), ('Jansanchar madhya', 'Jansanchar madhya'), ('Kavya shastra', 'Kavya shastra'), ('Vyakaran', 'Vyakaran')], default='English', max_length=255),
        ),
    ]
