# Generated by Django 5.1.4 on 2025-04-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_questionpg_main_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpg',
            name='subject',
            field=models.CharField(choices=[('MBA', 'MBA'), ('MCA', 'MCA'), ('MA English', 'MA English'), ('MA Hindi', 'MA Hindi'), ('M.Com', 'M.Com')], default='MBA', max_length=255),
        ),
    ]
